### ISSUE TITLE
react-redux animation lag when state changes

### ISSUE THREAD

**Issue by talarari** [rackt/react-redux#260] opened 2016-01-20 22:06 UTC
I'm using react-redux in a react native app. i have an icon toggle which animates a ripple when you toggle it. (from here: https://github.com/xinthink/react-native-material-kit#toggles, you can see it in the gif)

basically my state looks something like this:
```
{
    isChecked : false
}
```
and the component is something like this:

```
<MKIconToggle checked={checked}
              onCheckedChange={change => changeState(change.checked)}>
    <Image source='img1'/>
    <Image state_checked={true} source='img2'/>
</MKIconToggle>;

```
then i have a reducer to act on CHANGE_STATE actions and return a new state with true or false accordingly from the payload.

the thing is it lags horribly, i think because its re-rendering while the animation is still running. (i checked, when i do nothing in the reducer and just return the current state it runs smoothly)

how would you suggest solving this?

**Comment by gaearon** [comment] 2016-01-21 16:39
Are you sure it's related to Redux? Can you change the code to use React component local state and verify that the problem goes away?

**Comment by epeli** [comment] 2016-01-21 19:36
I'm seeing something similar in a React Native project I'm working on but I have a feeling it is because of some console.log() message marshalling caused by redux-logger. Will investigate more tomorrow.

**Comment by gaearon** [comment] 2016-01-25 02:06
`console.log()` will definitely slow things down, even on the web. Be careful with it :-)

**Comment by gaearon** [comment] 2016-01-28 00:20
I'm closing because there is not enough information to make this actionable for me. I don't know how exactly to reproduce the problem, in what environment it can be reproduced, and how exactly React Redux library fits into this picture. If you can give more details and confirm *this* library is indeed the bottleneck I'm happy to reconsider.

**Closed by gaearon** 2016-01-28 00:20 UTC
