### ISSUE TITLE
Question: ownProps in mapStateToProps 

### ISSUE THREAD

**Issue by gojohnnygo** [rackt/react-redux#265] opened 2016-01-23 01:53 UTC
I've read the [docs](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) about the `ownProps` argument, and I think I may be misusing it.

Could you use this `ownProps` to `connect()` dynamically created components?

I have a giant table. Number of columns/rows depend on what I get back from the server. The state is an array of objects, each representing a row, and each row is component I'm trying to `connect()`. The app updates as intended when I use `state` and does not when I use `ownProp`.  

```
// Row.jsx 
// first row example, row doesn't update when using ownProps
function mapStateToProps(state, ownProps) {
  return {
    rowData: ownProps.row,
  };
}
```

```
// Row.jsx
// first row example, row updates when using state
function mapStateToProps(state, ownProps) {
  return {
    rowData: state.table.rows[0],
  };
}
```

I'm guessing it has to do something with ownProps being a copy and not a reference to state?

`state.table.rows[0] === ownProps.row // false`

**Comment by gaearon** [comment] 2016-01-23 04:18
I don't understand the question, it's too specific to your problem. Unless you can post a JSBin reproducing the problem I don't think I can help.

State is just Redux state. ownProps are just props you pass to the component from the parent component. I'm not sure why row is in both places and how it's passed down. If it doesn't update it means that the corresponding prop wasn't updated in the parent component which can mean a bunch of different thing depending on your code.

I'm closing as this is unlikely to be an issue in the library but please feel free to share a JSBin reproducing this.

**Closed by gaearon** 2016-01-23 04:18 UTC

**Comment by gojohnnygo** [comment] 2016-01-24 03:15
Hey @gaearon,

Yeah, I guess my question is very specific. So let me generalize it a bit. :)

From your egghead.io Redux tutorial, how would you `connect()` each Todo so that only the changed Todo re-renders (instead of the entire list)?

Here's my [JSBin](https://jsbin.com/lucego/edit?js,console,output) of the Todo example. I've set an initial state, commented out where TodoList is `connect()`-ed, and `connect()`-ed the Todo component.

In `mapStateToTodoProps`, I don't know which Todo to reference in the Todos array, so I thought `ownProps` was how to do it. If you click on a Todo, the state correctly changes (see the console) but the Todo component does not re-render.

I hope this makes better sense. Thanks!

**Comment by gaearon** [comment] 2016-01-24 14:01
I think you got a bit confused. I'm not sure why you're doing it this way.

Todo used to be a purely presentational component. You changed it to be a container generated by connect(). Why? Now it accepts *some* todo props from its parent but *also* connects to the store. I don't understand why you needed a connect() there. Moreover *connect() is only needed if you want to subscribe component to the store updates*. It doesn't make sense to use connect() and only use ownProps to pass a prop down. It's received from parent anyway. You're subscribing to the store by using connect() but rather than use store's state, just pass down one of ownProps which Todo receives from a parent component. Effectively it does nothing at all: since you're not using store state inside mapStateToProps() you can as well completely remove it and the connect() call, and behavior won't change. So I don't understand what you were trying to do there.

The redrawing problem happens because you removed connect() from the generated VisibleTodoList and wrote it by hand. You are using getState() inside but you forgot to subscribe to the store to force updates when store state changes. This is why VisibleTodoList renders once with the initial state and isn't aware that you are toggling todos—it's not subscribed! To fix this you can add a store subscribe() call in componentDidMount() and call forceUpdate() when store state changes. However this is only meant as a learning exercise. It's a *lot* less efficient than using connect() which has many performance optimizations. So I encourage you to use connect() instead of subscribing to the store by hand.

If some of this is unclear I suggest you to take another look at all React videos in the course. I only show how to write container components by hand as part of the explanation build up. So you understand what connect() does under the hood. I don't actually advise you to write subscription code by hand in any real apps. Use connect(). I also don't recommend to use connect() when component receives store data by props—it is useless in this case. 

Hope it helps.

**Comment by gojohnnygo** [comment] 2016-01-24 21:37
Hey Dan, 

Yep I'm on board with everything you're saying. :)

> I think you got a bit confused. I'm not sure why you're doing it this way.

Sorry, I guess I'm not being clear again. Let's say the TodoList is large, and you're running into performance issues because the whole list re-renders (instead of an individual Todo).

To solve for this, my [JSBin](https://jsbin.com/lucego/edit?js,console,output) example attempts to move `connect()` at the top level (TodoList) down, so each Todo is `connect()`-ed. But if you say...

> I also don't recommend to use connect() when component receives store data by props—it is useless in this case.

It looks like I can't `connect()` individual Todos bc they get data by props. I incorrectly thought passing `ownProps` would be a way to subscribe to the store.

So I would have to subscribe each Todo by hand? I was trying to use `connect()`, but it's looking like this is not the right use case for it.

Thanks!

**Comment by gaearon** [comment] 2016-01-24 21:47
If you want to do that you can change VisibleTodoList to only select todo IDs from the store in its mapStateToProps. Then you can change TodoList to accept todoIds array rather than todos array as a prop. Then you can change TodoList to pass id as a prop to Todo component rather than {...todo}. Finally, then you can change mapStateToProps for Todo to return something like state.todos.find(todo => todo.id === ownProps.id).

However this won't be very efficient either for the reason that todos are kept in an array so every lookup is expensive. It's better to store them in an object keyed by todo ID and have a separate array of IDs in the state. Then you can use something like state.todosById[ownProps.id] in mapStateToProps of Todo.

Hope that helps! I would still start by adding shouldComponentUpdate() implementation to Todo component rather than connect() every individual Todo. You can use react-addons-shallow-compare for this. There is no guarantee that connecting every individual Todo is going to significantly improve your performance—implementing shouldComponentUpdate() is more likely to help.

**Comment by gojohnnygo** [comment] 2016-01-24 21:56
I got it. Thanks so much! :100:
